version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/cert.pem
      KC_HOSTNAME: $HOSTNAME
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/cert.key
    volumes:
      - $/CERTPATH/cert.pem:/opt/keycloak/conf/cert.pem
      - $/CERTPATH/cert.key:/opt/keycloak/conf/cert.key
    ports:
      - "443:8443"
      - "80:8080"
    restart: always
